[build]
builder = "nixpacks"
buildCommand = "cd backend/CourseVendor.API && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd backend/CourseVendor.API/out && dotnet CourseVendor.API.dll"
